### ISSUE TITLE
Serial.print doesn´t work

### ISSUE THREAD

**Issue by AceTecNic** [arduino-libraries/Arduino_MachineControl#103]
```cpp
void setup(){
  Serial.begin(19200);
}

void loop(){
  Serial.println("test");
}
```

this code is output to the IDE monitor, but not to the USB COM.
If I put this code on a UNO, I can get it with another program, just not with the Portenta Machine controller. 
Any suggestions?

**Comment by per1234** [comment]
Hi @AceTecNic. I'm sorry to see the serial communication on the Portenta Machine Control is not working for you.

This issue tracker is for subjects directly related to the **Arduino_MachineControl** library's codebase hosted in the repository. Since your report is about the general usage of the board, it will be best for you to contact Arduino support via this form:

https://www.arduino.cc/en/contact-us/
