### ISSUE TITLE
RTC methods should be singolar

### ISSUE THREAD

**Issue by agdl** [arduino-libraries/Arduino_MachineControl#50]
i.e setYear instead of setYears

**Comment by leonardocavagnis** [comment]
Hi @agdl,
This improvement will be included in the next release.

**Comment by per1234** [comment]
@leonardocavagnis we should wait to close the issue until the pull request has been merged. I have linked the two together so that GitHub will do that automatically.

FYI, there is a special syntax you can use in your pull request messages to generate such linkages:

https://docs.github.com/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
